name: Create and Publish Docker Image to Docker Container Registry

on:
  workflow_call:
    inputs:
      dockerfile-path:
        type: string
        default: 'Dockerfile'
      dockerfile-context:
        type: string
        default: '.'
      image-name:
        type: string
        required: true
      image-tag:
        type: string
        default: 'latest'
    secrets:
      registry-username:
        required: true
      registry-password:
        required: true
jobs:
  build:
    runs-on: ubuntu-latest

    steps:      
      - uses: actions/checkout@v4
      
      - name: Setup BuildX
        uses: docker/setup-buildx-action@v3

      - name: Login to the Registry
        uses: docker/login-action@v3
        with:
          username: ${{secrets.registry-username}}
          password: ${{secrets.registry-password}}
      
      - name: Build and Push the Image
        uses: docker/build-push-action@v6
        with:
          context: ${{ inputs.dockerfile-context }}
          file: ${{ inputs.dockerfile-path }}
          push: true
          tags: ${{secrets.registry-username}}/${{ inputs.image-name }}:${{ inputs.image-tag }}
